// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LN_RoguelikeEngine","status":true,"description":"LN_RoguelikeEngine v0.0.1","parameters":{}},
{"name":"LN_FilmicFilter","status":true,"description":"LN_FilmicFilter v1.0.1 (MIT License)","parameters":{}}
];
