site_name: My Docs
docs_dir: mkdocs
site_dir: mksite

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

theme:
    name: material
    features:
        - navigation.tabs
        - content.code.annotate 
    language: ja
    icon:
        logo: material/school
        repo: fontawesome/brands/git-alt
    #favicon: favicon.png
    
nav:
    - Home: index.md
    - Manual:
        - index: manual/index.md
        - ドロップアイテム: manual/DropItem.md
    - リファレンス:
        - index: reference/Traits.md
    - 拡張:
        - index: dev/index.md
    - 内部的なこと:
        - index: dev/index.md
        - XX: dev/xx.md
        - 未整理メモ: dev/Unorganized.md
