site_name: RPGツクールMZ MisteryRogueSystem
docs_dir: mkdocs
site_dir: mksite

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - attr_list

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.indexes
        - content.code.annotate 
    language: ja
    icon:
        logo: material/school
        repo: fontawesome/brands/git-alt
    #favicon: favicon.png

extra_css:
    - stylesheets/extra.css

nav:
    - Home: index.md
    - チュートリアル: 
        - tutorial/index.md
        - 入門チュートリアル:
            - 1. データの設定方法: tutorial/1-first/1-project.md
            - 2. 基本概念: tutorial/1-first/2-basic.md
            - 3. 標準ゲームシステムとの関係: tutorial/1-first/3-system.md
            - 4. ダンジョン攻略の流れ: tutorial/1-first/4-land.md
            - 5. データベースの編集: tutorial/1-first/5-database.md
            - 6. 詳細データの編集: tutorial/1-first/6-edit-details.md
            - 7. デバッグ機能: tutorial/1-first/7-debug-command.md
    - 機能:
        - feature/index.md
        - 種族: feature/race.md
        - スキル: feature/skill.md
        - トループ: feature/troop.md
        - ステート: feature/state.md
        - ステートグループ: feature/state-group.md
        - ドロップアイテム: feature/DropItem.md
        - 変数: feature/rmmz-variables.md
    - 実装:
        - implementation/index.md
        - アイテム:
            - 回復アイテム: implementation/items/recovery-item.md
    - リファレンス:
        - reference/index.md
        - イベントコマンド: reference/EventCommands.md
        - "@MR属性": reference/MRAttributes.md
        - Traits: reference/Traits.md
    - 拡張:
        - index: extensions/index.md
    # - 内部的なこと:
    #     - index: dev/index.md
    #     - XX: dev/xx.md
    #     - 未整理メモ: dev/Unorganized.md
