site_name: RPGツクールMZ 不思議のダンジョンプラグイン
docs_dir: mkdocs
site_dir: mksite

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - attr_list

theme:
    name: material
    features:
        - navigation.tabs
        - content.code.annotate 
    language: ja
    icon:
        logo: material/school
        repo: fontawesome/brands/git-alt
    #favicon: favicon.png

extra_css:
    - stylesheets/extra.css

nav:
    - Home: index.md
    - 入門: 
        - index:  tutorial/index.md
        - 入門チュートリアル:
            - 1. サンプルプロジェクト: tutorial/1-first/1-project.md
            - 2. 基本概念: tutorial/1-first/2-basic.md
            - 3. ダンジョン攻略の流れ: tutorial/1-first/3-land.md
            - 4. データベースの編集: tutorial/1-first/4-database.md
    - 実装:
        - index: implementation/index.md
        - アイテム:
            - 回復アイテム: implementation/items/recovery-item.md
    - Manual:
        - index: manual/index.md
        - ステート: manual/State.md
        - ドロップアイテム: manual/DropItem.md
    - リファレンス:
        - index: reference/Traits.md
    - 拡張:
        - index: dev/index.md
    - 内部的なこと:
        - index: dev/index.md
        - XX: dev/xx.md
        - 未整理メモ: dev/Unorganized.md
