site_name: RPGツクールMZ MisteryRogueSystem
docs_dir: mkdocs
site_dir: mksite

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.annotate 
  language: ja
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  #favicon: favicon.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - チュートリアル: 
    - 1-tutorial/index.md
    - 入門チュートリアル:
      - 1. はじめに: 1-tutorial/1-first/1-introduction.md
      - 2. データの設定方法: 1-tutorial/1-first/2-project.md
      - 3. 基本概念: 1-tutorial/1-first/3-basic.md
      - 4. 標準ゲームシステムとの関係: 1-tutorial/1-first/4-system.md
      - 5. ダンジョン攻略の流れ: 1-tutorial/1-first/5-land.md
      - 6. データベースの編集: 1-tutorial/1-first/6-database.md
      - 7. 詳細データの編集: 1-tutorial/1-first/7-edit-details.md
      - 8. デバッグ機能: 1-tutorial/1-first/8-debug-command.md
  - 機能:
    - feature/index.md
    - パラメータ: feature/parameters.md
    - 種族: feature/race.md
    - スキル: feature/skill.md
    - トループ: feature/troop.md
    - ステート: feature/state.md
    - ステートグループ: feature/state-group.md
    - ドロップアイテム: feature/DropItem.md
    - 変数: feature/rmmz-variables.md
    - イベントコマンド: feature/event-commands.md
  - 実装:
    - implementation/index.md
    - アイテム:
      - 回復アイテム: implementation/items/recovery-item.md
  - リファレンス:
    - 4-reference/index.md
    - プラグインコマンド: 4-reference/plugin-commands.md
    - イベントコマンド: 4-reference/EventCommands.md
    - "@MR属性": 4-reference/MRAttributes.md
    - Traits: 4-reference/Traits.md
  - 拡張:
    - index: extensions/index.md
  - 未整理メモ:
    - 99-note/index.md
    - ステータスリセットのタイミング: 99-note/status-reset.md
  # - 内部的なこと:
  #     - index: dev/index.md
  #     - XX: dev/xx.md
  #     - 未整理メモ: dev/Unorganized.md
